### ISSUE TITLE
Include React as a peer dependency

### ISSUE THREAD

**Issue by sean0x42** [scottjr632/react-rellax-wrapper#11]
#### What needs to change?

React (and possibly React DOM) should be included as a peer dependency, rather than a direct dependency. 

#### Why should it change?

The problem is that if a consumer of `react-rellax-wrapper` is using a different version of React (such as the latest v17), React will actually be installed twice.

When this happens, hook calls may become broken. See: <https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react>

#### Useful links

See: <https://nodejs.org/en/blog/npm/peer-dependencies/>

```
```

Also, great library by the way! Thanks

**Comment by scottjr632** [comment]
Thanks for bringing this up! I was unaware this was an issue and will look into this as soon as I get a chance!

**Comment by sean0x42** [comment]
Great, thanks @scottjr632. There is a workaround for yarn users, so it's not super critical. I'd be happy to submit a PR too if I can find some time, probably not this week though 😅 

Workaround: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by scottjr632** [comment]
@sean0x42 Definitely feel free to submit a PR if you get to it before me!
I will leave this issue open until I fix the issue or you make a PR. Thanks!

**Comment by scottjr632** [comment]
[v1.0.6](https://github.com/scottjr632/react-rellax-wrapper/releases/tag/v1.0.6) fixes this issue.

**Comment by sean0x42** [comment]
> [v1.0.6](https://github.com/scottjr632/react-rellax-wrapper/releases/tag/v1.0.6) fixes this issue.

Thanks @scottjr632!
