### ISSUE TITLE
Setting Wrapper

### ISSUE THREAD

**Issue by JeroenDerks** [scottjr632/react-rellax-wrapper#4]
Hi,

Thanks for making the rellax wrapper!

I was wondering how you reference the wrapper when setting `relativeToWrapper={true}`?

Accessing through id, className or ref does not work.

**Comment by scottjr632** [comment]
Currently, wrapper can only be referenced using a CSS query selector. 
For example
```jsx
  <div className={'horizontal__container'} id='wrapper'>
    <h3>Horizontal Scrolling</h3>
    <RellaxWrapper speed={-7} horizontal={true} wrapper={'#wrapper'} relativeToWrapper={true}>
      <div className={'icon'}>
        🐌
      </div>
    </RellaxWrapper>
    <RellaxWrapper speed={7} horizontal={true} wrapper={'#wrapper'} relativeToWrapper={true}>
      <div className={'icon'}>
        🚀
      </div>
    </RellaxWrapper>
  </div>
```
Check out the [horizontal story on storybook](https://scottjr632.github.io/react-rellax-wrapper/?path=/story/rellax-wrapper--horizontal) for an example
