### ISSUE TITLE
parametters like "xs, mobile, etc..." does not work.

### ISSUE THREAD

**Issue by Jupihawx** [scottjr632/react-rellax-wrapper#5]
Hello. 
I am trying to have different speeds for different viewports. For example, if I want a parallax on desktop, but not on something smaller, I think it would go like this (I am using Gatsby).

`        <RellaxWrapper xs={0} mobile={0} tablet={0} speed={-10}>
          <Img className={classes.sky} fluid={data.sky.childImageSharp.fluid} />
        </RellaxWrapper>

        <RellaxWrapper xs={0} mobile={0} tablet={0} speed={-7}>
          <Img
            className={classes.moutain}
            fluid={data.moutain.childImageSharp.fluid}
          />
        </RellaxWrapper>

        <RellaxWrapper xs={0} mobile={0} tablet={0} speed={0}>
          <Img
            className={classes.front}
            fluid={data.front.childImageSharp.fluid}
          />
        </RellaxWrapper>`

But it does not seem to work at all, I have a fixed image from +/- 570 px to 1200px. But under that 570px the parallax effect appears again. Do you know why?
Thanks!

**Comment by Jupihawx** [comment]
Found the mistake in your code 👍

`      data-rellax-xs-speed={speed && speed.toString()}`

**Comment by scottjr632** [comment]
Just published v1.0.4
Fix should be included.

Good catch! Thanks! @Jupihawx

**Comment by Jupihawx** [comment]
Great, thanks to you!
